// <auto-generated />
namespace _2015137075.PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uno));
        
        string IMigrationMetadata.Id
        {
            get { return "201706100431027_uno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
